feat(chart-type): add spreadsheet
antvis/AVA pull request #124
Opened 2021-01-01 09:05 UTC by BBSQQ

2021-01-06 09:06 UTC, neoddish commented on packages/knowledge/src/chartID.ts
> +  'spreadsheet',
重新考虑spreadsheet的命名

2021-01-06 09:06 UTC, neoddish commented on packages/knowledge/src/base.ts
> +  spreadsheet: {
重新考虑spreadsheet的命名

2021-01-07 12:53 UTC, BBSQQ commented on packages/knowledge/src/pack.ts
> +        if (key !== 'alias' && key !== 'channel' && typeof value != 'boolean') {
@neoddish  原来 channel 必须的，这里做了一下判断

2021-01-08 06:03 UTC, neoddish requested changes

2021-01-08 06:03 UTC, neoddish commented on packages/chart-advisor/src/custom-plot/table.ts
> +        this.container.innerText = '数据量过大暂不支持绘制';
i18n

2021-01-08 06:03 UTC, neoddish commented on packages/knowledge/src/i18n/zh-CN.ts
> +      name: '交叉表',
```suggestion
      name: '表格',
```

2021-01-08 06:03 UTC, neoddish commented on packages/knowledge/src/i18n/zh-CN.ts
> +      alias: ['信息表', '分析表'],
```suggestion
      alias: ['交叉表'],
```

2021-01-08 07:18 UTC, neoddish approved these changes

2021-01-08 07:19 UTC, merged