feat(dw-transform): add unstack util
antvis/AVA pull request #143
Opened 2021-04-07 08:30 UTC by BBSQQ

2021-04-08 03:06 UTC, neoddish requested changes

2021-04-08 03:06 UTC, neoddish commented on packages/datawizard/transform/src/reshape/stack.ts
> + * @public
doc 写一写吧

2021-04-18 15:35 UTC, BBSQQ commented on packages/datawizard/transform/src/reshape/stack.ts
> + * @public
done

2021-04-18 15:46 UTC, neoddish approved these changes
LGTM

2021-04-18 15:46 UTC, merged