WIP: feat(auto-chart): add auto-chart AdviceList part
antvis/AVA pull request #262
Opened 2021-09-09 11:42 UTC by beewolf233

### PR includes

- [ ] fixed #0
- [ ] add / modify test cases
- [ ] documents, demos

2021-09-09 15:50 UTC, BBSQQ commented
提交 pr 加一个截图 or gif 在描述里会更好

2021-09-09 16:03 UTC, BBSQQ commented on packages/auto-chart/src/AutoChart.tsx
> +  fields?: any[];
```suggestion
  fields?: string[];
```

这个 props 配置与 chart-advisor 一致即可

2021-09-09 16:03 UTC, BBSQQ commented on packages/auto-chart/src/AutoChart.tsx
> +  }, [width, height]);
确认一下逻辑：如果没有指定 width 和 height 也可以有默认宽高吧？

2021-09-10 02:36 UTC, BBSQQ requested changes

2021-09-10 02:36 UTC, BBSQQ commented on packages/auto-chart/src/ChartConfigPanel/index.tsx
> +        图表配置
所有文字需要 i18n 做配置，之前也是有这个能力的

2021-09-10 02:36 UTC, BBSQQ commented on packages/auto-chart/package.json
> +    "@antv/chart-advisor": "^2.0.0-alpha.1",
@neoddish why ca  ^2.0.0 init pkg version with alpha? cc @soundquiet

2021-09-10 02:36 UTC, BBSQQ commented on packages/auto-chart/src/AdviceList/index.tsx
> +  advices: any[];
明确一下 any 类型

2021-09-10 02:36 UTC, BBSQQ commented on packages/auto-chart/src/AdviceList/index.tsx
> +  containerHover: boolean;
```suggestion
  isActive: boolean;
```

如果是 bool 类型可以重新考虑一下 props 命名，类似 isActive 之类的可以让人一看就知道。containerHover 感觉是个动作而非 bool

2021-09-10 02:36 UTC, BBSQQ commented on packages/auto-chart/src/AdviceList/index.tsx
> +  onChartChange: (valueIndex: number) => void;
```suggestion
  onChartTypeChange: (valueIndex: number) => void;
```

这里 chart list 主要是修改图表类型的，如果是 config panel 也会造成 chart change，可以从命名上区分开

2021-09-10 02:36 UTC, BBSQQ commented on packages/auto-chart/src/AdviceList/index.tsx
> +                    <div className="advice-chart-name" data-index={index}>折线图</div>
这里折线图是写死的吗？

2021-09-10 02:38 UTC, neoddish commented on demo/src/demos/AutoChart/data.json
> +[
对

2021-09-10 02:40 UTC, neoddish commented on packages/auto-chart/package.json
> +    "@antv/chart-advisor": "^2.0.0-alpha.1",
2.0.0-alpha.1 < 2.0.0

2021-09-10 06:12 UTC, beewolf233 commented
![chrome-capture (2)](https://user-images.githubusercontent.com/24711525/132808102-02e5bc06-b5d6-4bf8-a015-bcd16fda17cf.gif)

2021-09-15 02:41 UTC, beewolf233 commented
![chrome-capture (3)](https://user-images.githubusercontent.com/24711525/133361531-59beb2fc-14dc-4bb3-b667-e8311655d39a.gif)

2021-09-15 02:41 UTC, beewolf233 commented on packages/auto-chart/src/utils.ts
> +import Thumbnails from '@antv/thumbnails';
已经加上

2021-09-15 02:41 UTC, beewolf233 commented on packages/auto-chart/src/AutoChart.tsx
> +  fields?: any[];
已经修改

2021-09-15 02:42 UTC, beewolf233 commented on packages/auto-chart/src/AutoChart.tsx
> +  }, [width, height]);
是的 默认宽高 都为400

2021-09-15 02:42 UTC, beewolf233 commented on packages/auto-chart/src/index.less
> +@autochart-prefix: __AUTO_CHART__;
后续 build我再加上

2021-09-15 02:42 UTC, beewolf233 commented on packages/auto-chart/src/ChartConfigPanel/index.tsx
> +        图表配置
加上i18n了

2021-09-15 02:43 UTC, beewolf233 commented on packages/auto-chart/src/AdviceList/index.tsx
> +  advices: any[];
已经添加

2021-09-15 02:43 UTC, beewolf233 commented on packages/auto-chart/src/AdviceList/index.tsx
> +  containerHover: boolean;
名称已修改

2021-09-15 02:43 UTC, beewolf233 commented on packages/auto-chart/src/AdviceList/index.tsx
> +  onChartChange: (valueIndex: number) => void;
名称已修改

2021-09-15 02:44 UTC, beewolf233 commented on packages/auto-chart/src/AdviceList/index.tsx
> +                    <div className="advice-chart-name" data-index={index}>折线图</div>
是的 当时是初稿 现在已修改

2021-09-15 07:03 UTC, BBSQQ approved these changes
LGTM

2021-09-15 13:20 UTC, merged