test(insight): add test case of trend info
antvis/AVA pull request #573
Opened 2023-03-18 10:02 UTC by LAI-X

### PR includes

- [ ] fixed #0
- [ ] add / modify test cases
- [ ] documents, demos

2023-03-18 10:08 UTC, BBSQQ requested changes

2023-03-18 10:08 UTC, BBSQQ commented on packages/ava/__tests__/integration/insight/trend.test.ts
> +    expect(result.insights[0]?.patterns?.[0] as ChangePointInfo).toBeCloseToOutlierOrChangePointInfo({
1. 只测试到一个 pattern 应该不够？
2. 应该外层的 dimension measure 信息也需要吧？比如 measure 不同聚合类型下的 insight

cc @chenluli

2023-03-18 10:09 UTC, BBSQQ commented on packages/ava/__tests__/integration/insight/trend.test.ts
> +    // 只比对趋势类型（increasing/decreasing）是否相同以及显著性水平相近
👍

2023-03-19 04:22 UTC, LAI-X commented on packages/ava/__tests__/integration/insight/trend.test.ts
> +    expect(result.insights[0]?.patterns?.[0] as ChangePointInfo).toBeCloseToOutlierOrChangePointInfo({
done，修改测试方法，
1: 补充dimension，measure，subspace的比对
2: 补充存在多个pattern的测试用例

2023-03-19 05:06 UTC, BBSQQ approved these changes
LGTM

2023-03-19 05:37 UTC, merged